#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <stdio.h>


#define DATA_CHUNK_SIZE_BYTES    (512u)

// enumeration for error codes
typedef enum 
{
    SUCCESS_STATUS = 0,
    FAILURE_STATUS = -99,
    ERROR_INVALID_ARGUMENTS,
    ERROR_INVALID_LENGTH,
    ERROR_NULL_POINTER,
    ERROR_RESET_FILE_POINTER,
    ERROR_EMPTY_FILE,
    ERROR_FILE_NOT_FOUND,
    ERROR_FILE_NOT_OPENED,
    ERROR_FILE_NOT_CLOSED,
    ERROR_FILE_READ_FAILED,
    ERROR_FILE_WRITE_FAILED,
    ERROR_FILE_EXTENSION,
    ERROR_MEMORY_ALLOCATION_FAILED,
    ERROR_COMPRESSION_FAILED,
    ERROR_DECOMPRESSION_FAILED,
} enu_error_codes;

#endif // CONSTANTS_H